### ISSUE TITLE
Error split arguments ggplot2

### ISSUE THREAD

**Issue by GabrielSartori** [EvaMaeRey/ggplot_flipbook#2]
Hello, 

When i split the argument of ggplot2, like that, in (01_christmas_tree_sales.Rmd).

>  geom_smooth(
>     method = "lm", 
>     se = F)

I cant execute, error message: Error in parse (text = x, srcfile = src)

Did you understand?

**Comment by EvaMaeRey** [comment]
This may be related to the reveal function, which assumes that you have complete ggplot expressions for each line of code.  So, yes, in general you can split lines and execute in ggplot, but the set up of the project (for the flip book) may prohibit this.  Are you finding the data from #MakeoverMonday okay?

**Comment by EvaMaeRey** [comment]
You are right that it would be nice to rewrite the function to allow split argument.  It's on the ideas list.

**Comment by GabrielSartori** [comment]
oh nice, i will apreciated! I am using the template to build a tutorial with maps visualization !

**Comment by EvaMaeRey** [comment]
Nice.  Let me know when you have something to share!  I would like to learn more about sf package.  Will you be using that?  For now you might adjust the size of the code font, and the relative size of code v. figure.  And you can currently scroll to code that doesn't fit.  Not ideal.
