### ISSUE TITLE
Easier way to have colour gradient

### ISSUE THREAD

**Issue by modche** [EvaMaeRey/ggplot_flipbook#5]
Hi Eva,
nice page and nice codes!

Regarding [ggplot_flipbook/ggplot_flipbook_xaringan.html#68](https://evamaerey.github.io/ggplot_flipbook/ggplot_flipbook_xaringan.html#68)
Instead of 
```{R}
scale_fill_manual(
    values = colorRampPalette(
      RColorBrewer::brewer.pal(n = 9, name = "Purples"))(6), 
                    guide = guide_legend(reverse = TRUE))`
```  

you can simply use 

`scale_fill_brewer(palette = "Purples", direction = -1)`

Direction can be `+1` or `-1`

**Comment by EvaMaeRey** [comment]
This didn't give exactly the same purples, so I just kept in the way I have it.  Thanks you for the suggestion, what I have is a bit long for sure.
